# Generated by Django 4.1 on 2022-08-28 13:09

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('deleted_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
